#
# Build OML's client library
#
# $Id: Makefile 641 2005-10-07 03:37:56Z max $
#

PKG_NAME = client
APT_NAME = liboml2

DIRS = src/c src/ruby

TOP_DIR = $(shell pwd)/..
include $(TOP_DIR)/config.mk
include $(TOP_DIR)/tool/dir-makefile.mk
include $(TOP_DIR)/tool/apt-makefile.mk



