/*
 * This file was automatically generated by oml2-scaffold 2.12.0
 * for generator version 2.12.0.
 * 
 */

#define PACKAGE			"generator"
#define VERSION			"2.12.0"

/* Provide compatibility with autoconf-generated config.h */
#define PACKAGE_NAME		PACKAGE
#define PACKAGE_TAR_NAME	PACKAGE
#define PACKAGE_VERSION		VERSION
#define PACKAGE_STRING PACKAGE_NAME " " PACKAGE_VERSION

