
defApplication('oml:app:generator', 'generator') do |a|

  a.version(1, 0, 0)
  a.shortDescription = 'Example OML application'
  a.description = %{
This programs implements a simple sin-wave generator with
the output measured by OML.

It is almost only generated by oml2-scaffold.
}

  a.defProperty('amplitude', 'Amplitude of produced signal', ?a,
        :type => :float, :impl => { :var_name => 'amplitude' })
  a.defProperty('frequency', 'Frequency of wave generated', ?f,
        :type => :float, :unit => 'hertz',
        :impl => { :var_name => 'frequency' })
  a.defProperty('samples', 'Number of samples to take. -1 ... forever', ?n,
        :type => :int32, :impl => { :var_name => 'samples' })
  a.defProperty('sample-interval', 'Time between consecutive measurements', ?i,
        :type => :float, :unit => 'second',
	:impl => { :var_name => 'sample_interval' })

  a.defMeasurement("d_lin") do |m|
    m.defMetric('label', :string)
    m.defMetric('seq_no', :uint32)
  end

  a.defMeasurement("d_sin") do |m|
    m.defMetric('label', 'string')
    m.defMetric('phase', 'double')
    m.defMetric('value', 'double')
  end

  a.path = "/usr/local/bin/generator"
end

# Local Variables:
# mode:ruby
# End:
# vim: ft=ruby:sw=2
