#
# Build the OML2 server
#
# $Id: Makefile 641 2005-10-07 03:37:56Z max $
#

PKG_NAME = proxy_server
APT_NAME = oml2_proxy_server

DIRS = src/c

TOP_DIR = $(shell pwd)/..
include $(TOP_DIR)/config.mk
include $(TOP_DIR)/tool/dir-makefile.mk
include $(TOP_DIR)/tool/apt-makefile.mk



