#
# Build the omf_nmetrics application
#
# $Id: Makefile 641 2005-10-07 03:37:56Z max $
#

DIRS = src/c

TOP_DIR = $(shell pwd)/../..
include $(TOP_DIR)/config.mk
include $(TOP_DIR)/tool/dir-makefile.mk
include $(TOP_DIR)/tool/apt-makefile.mk



